global:
  envName: dev       

  projects:
    istio:
      enabled: true 
    prometheus:
      enabled: true  
    grafana:
      enabled: true  
    thanos:
      enabled: true       

  applications:
    istio-base:
      enabled: true 
    istio-operator:
      enabled: true 
    istio-profile:
      enabled: true 
    prometheus:
      enabled: true  
    grafana:
      enabled: true  
    thanos:
      enabled: true                   