apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-fluent-bit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: fluent-bit
  
  source:
    helm:
      version: v3
      valueFiles:
      - values-security-{{ .Values.env }}.yaml
    path: helm-charts/fluent-bit
    repoURL: https://github.com/paas2/fluentbit 
    targetRevision: HEAD
    
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:  
      prune: true 

