apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: grafana

  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
      - values-monitoring-{{ .Values.env }}.yaml
    path: helm-charts/grafana
    repoURL: https://github.com/paas2/prometheus 
    targetRevision: HEAD
    
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:  
      prune: true 
